name: 'Install Nix'
description: 'Installs Nix on GitHub Actions for the supported platforms: Linux and macOS.'
author: 'Domen Kožar'
inputs:
  install_url:
    description: 'Installation URL that will contain a script to install Nix.'
  install_options:
    description: 'Additional installer flags passed to the installer script.'
  nix_path:
    description: 'Set NIX_PATH environment variable.'
  extra_nix_config:
    description: 'gets appended to `/etc/nix/nix.conf` if passed.'
branding:
  color: 'blue'
  icon: 'sun'
runs:
  using: 'composite'
  steps:
    - run : ${{ github.action_path }}/install-nix.sh
      shell: bash
      env:
        INPUT_INSTALL_URL: ${{ inputs.install_url }}
        INPUT_INSTALL_OPTIONS: ${{ inputs.install_options }}
        INPUT_NIX_PATH: ${{ inputs.nix_path }}
        INPUT_EXTRA_NIX_CONFIG: ${{ inputs.extra_nix_config }}
