name: "Install Nix"
description: "Installs Nix on GitHub Actions for the supported platforms: Linux and macOS."
author: "Domen Kožar"
inputs:
  extra_nix_config:
    description: "Gets appended to `/etc/nix/nix.conf` if passed."
  github_access_token:
    description: "Configure nix to pull from github using the given github token."
  install_url:
    description: "Installation URL that will contain a script to install Nix."
  install_options:
    description: "Additional installer flags passed to the installer script."
  nix_path:
    description: "Set NIX_PATH environment variable."
branding:
  color: "blue"
  icon: "sun"
runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/install-nix.sh
      shell: bash
      env:
        INPUT_EXTRA_NIX_CONFIG: ${{ inputs.extra_nix_config }}
        INPUT_GITHUB_ACCESS_TOKEN: ${{ inputs.github_access_token }}
        INPUT_INSTALL_OPTIONS: ${{ inputs.install_options }}
        INPUT_INSTALL_URL: ${{ inputs.install_url }}
        INPUT_NIX_PATH: ${{ inputs.nix_path }}
        GITHUB_TOKEN: ${{ github.token }}
